Repository noblox/noblox.js, pull requests merged in 2021-08, with the labels that each got.

#393 Typings updates - Add displayName
  lib/group/searchGroups.js
  lib/user/getPlayerBadges.js
  test/user.test.js
  typings/index.d.ts
  typings/jsDocs.ts
Labels: patch

#413 Fix typo that is causing errors
  lib/asset/configureItem.js
Labels: patch

#404 Implement searchGroups
  lib/group/searchGroups.js
  lib/util/getPageResults.js
  test/group.test.js
  typings/index.d.ts
  typings/jsDocs.ts
Labels: enhancement, minor

#394 Add uploadAnimation & getGroupAssets
  lib/asset/uploadAnimation.js
  lib/asset/uploadModel.js
  lib/group/getGroupAssets.js
  test/asset.test.js
  test/assets/KeyframeSequence.rbxm
  test/group.test.js
  test/user.test.js
  typings/index.d.ts
  typings/jsDocs.ts
Labels: minor, release

#414 Use GH_TOKEN instead of GITHUB_TOKEN for auto
  .github/workflows/npmpublish.yml
Labels: internal
