Repository noblox/noblox.js, pull requests merged in 2022-02, with the labels that each got.

#500 Fix onGroupTransaction and make getPageResults use bluebird
  lib/group/onGroupTransaction.js
Labels: bug, patch, release

#503 Add setGroupDescription and setGroupName
  lib/group/setGroupDescription.js
  lib/group/setGroupName.js
  typings/index.d.ts
  typings/jsDocs.ts
Labels: enhancement, minor

#505 Add updateUniverse & getUniverseInfo
  lib/game/getPlaceInfo.js
  lib/game/getUniverseInfo.js
  lib/game/updateUniverse.js
  lib/util/getDate.js
  test/game.test.js
  typings/index.d.ts
  typings/jsDocs.ts
Labels: enhancement, minor, release
