Repository noblox/noblox.js, pull requests merged in 2024-08, with the labels that each got.

#817 Update dependencies and minimum node version requirements
  .eslintrc.js
  .github/workflows/doc-publish.yml
  .github/workflows/npmpublish.yml
  .github/workflows/run-tests.yml
  .travis.yml
  README.md
  eslint.config.mjs
  lib/privatemessages/getMessages.js
  lib/privatemessages/onMessage.js
  package.json
  postinstall.mjs
  yarn.lock
Labels: dependencies, major

#814 Remove checkDeveloperProductName reference from addDeveloperPoduct (redundant and deprecated)
  lib/games/addDeveloperProduct.js
  lib/games/checkDeveloperProductName.js
  lib/index.js
  typings/index.d.ts
Labels: help wanted, major, release

#825 Add getAuthenticatedUser typing
  typings/index.d.ts
Labels: patch, release

#827 Use admin token for auto
  .github/workflows/npmpublish.yml
Labels: patch
